### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by diver1008** [sayontan/suffusion#95]
Greetings and thank you  to al who keep this theme alive it is the best ever.

Will the theme work with PHP 8.3 or any of the PHP versions 8.  I presently run it with PHP 7.4.

Thanks.  

PS not sure if this is the pace to post such a question, if not please point me in the right direction.

**Comment by mbtools** [comment]
I'm running it on PHP 8.1.31 and WP 6.6.2. It works great.

I haven't looked at PHP 8.3 but if there are any problems, just open an issue here.

**Comment by mbrsolution** [comment]
Hello all, I can confirm Suffusion is working well in my dev site running PHP 8.2.12 and WordPress 6.7.1 :) And my live site is running PHP 8.2.27 and also WordPress 6.7.1.

So I can confirm Suffusion works really well with the above mentioned versions of PHP and WordPress.

Kind regards,
Manuel

**Comment by diver1008** [comment]
Thanks, everybody for answering! 

It is not working here.  As said it works with another theme to go to 8.xx.

Here some information that might help solve it.  I use a child Sufu-Scion.  If I bypass this by activating Suffusion directly it locks me out of the control pannel and I can not acces the site anymore.  A restore gets me back in.  

My server uses My SQL 5.7
My phpMyAdmin tells me: Current server: MariaDB-10.4 MySQL-5.7 MariaDB-10.6

Any tips or ideas?

**Comment by diver1008** [comment]
Thanks for the tip I did not know this.

I did as suggested:  define( 'WP_DEBUG', true );

And I am now beyond my skill level now.  See what I got below.  And this action locked me out again.  This happened as soon as I switched to the child theme.  

Any suggestions?

Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-widget.php:163 Stack trace: #0 /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-widget-factory.php(62): WP_Widget->__construct() #1 /client/123456_654321/site XYZ/ XYZ/wp-includes/widgets.php(123): WP_Widget_Factory->register() #2 /client/123456_654321/site XYZ/ XYZ/wp-content/themes/suffusion/widgets/suffusion-widgets.php(29): register_widget() #3 /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-hook.php(324): Suffusion_Widgets->load_widgets() #4 /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #5 /client/123456_654321/site XYZ/ XYZ/wp-includes/plugin.php(517): WP_Hook->do_action() #6 /client/123456_654321/site XYZ/ XYZ/wp-includes/widgets.php(1870): do_action() #7 /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-hook.php(324): wp_widgets_init() #8 /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #9 /client/123456_654321/site XYZ/ XYZ/wp-includes/plugin.php(517): WP_Hook->do_action() #10 /client/123456_654321/site XYZ/ XYZ/wp-settings.php(704): do_action() #11 /client/123456_654321/site XYZ/ XYZ/wp-config.php(100): require_once('/kunden/203411_...') #12 /client/123456_654321/site XYZ/ XYZ/wp-load.php(50): require_once('/kunden/203411_...') #13 /client/123456_654321/site XYZ/ XYZ/wp-admin/admin.php(34): require_once('/kunden/203411_...') #14 /client/123456_654321/site XYZ/ XYZ/wp-admin/themes.php(10): require_once('/kunden/203411_...') #15 {main} thrown in /client/123456_654321/site XYZ/ XYZ/wp-includes/class-wp-widget.php on line 163

I changed personal information some information that I do not want to be in the public domain in the error message.

**Comment by mbtools** [comment]
These issues all point to `backupwordpress` plugin. Can you disable this plugin and try again?

**Comment by mbtools** [comment]
This might be a fix. Add the following code to the end of `/widget/suffusion-widgets.php` in the theme folder:

```php
class Suffusion_Widget extends WP_Widget {
	function __construct() {
		parent::__construct(
			'suffusion_widget', // Base ID
			__('Suffusion Widget', 'suffusion'), // Widget name in admin
			array(
				'description' => __('A basic Suffusion widget', 'suffusion'),
			)
		);
	}
}

class Suffusion_Category_Widget extends WP_Widget {
	function __construct() {
		parent::__construct(
			'suffusion_category', 
			__('Suffusion Category', 'suffusion'),
			array(
				'description' => __('Display categories with additional formatting options', 'suffusion'),
			)
		);
	}
}
```

If this works, I can make a new version with it. However, we might run into more issues afterwards... Let me know

**Comment by diver1008** [comment]
Thanks will test later when back home.

**Comment by diver1008** [comment]
Thanks for the code, I am not sure if I should implement it right now.  

Here is what I did.  I have a domain with only a test website attached to it.  So, I activated the 2024 theme.  I installed the most important Widgets I use on the other site.  I ran a widget that checks (PHP Compatibility Checker) and all widgets are OK for PHP 8.  Including the ones that are not activated as only a few are activated.

FYI, the installation information in case it gives a clue.  
Hostname für MariaDB 10.6 > mariadb106
Hostname für MariaDB 10.4 > localhost
Hostname für MySQL > mysql
Mysql version 5.7

When I test this setup by calling up the site in a browser it opens fine under PHP 7.4.  Under PHP 8 it does not load and my WP/Admin also refuses to reload until I switch back to PHP 7.4.

The PHP compatibility checker also creates a report whereby almost all the widgets there is an error in one or more lines.  I enclose the code just in case.

Any ideas or suggestions?  

[report-2.txt](https://github.com/user-attachments/files/18708388/report-2.txt)

**Comment by mbtools** [comment]
PHP Compatibility Checker only checks up to PHP 8.0... not 8.3 like we are interested in. It also covers only published plugins and themes... so not Suffusion.

I'm having AI rework the complete code but it's making hundreds of changes 😄 . I have no idea if it will work afterwards. 🤷 I'm off for two week and will get back to testing after

**Comment by diver1008** [comment]
morning folks.  my ISP has just been bought by GoDaddy.  so i am being switched to new servers and new tariffs.  I will wait till that has happened before I touch the website.  I will report back at that point.  thanks for the help so far.

**Comment by ChangeAgents816** [comment]
Greetings, I am back.  

Well, my ISP really will get a price for the worst ever experience.  I won’t bother you with the details, but one thing they did was turn off my domain (it was a free domain, so no, I did not forget to pay) among a whole series of other disasters.  I am now with a new one and they are great.  Good support for the migration and all the things you wish for as a not very savvy website owner.  Having lost the domain, I used to log in with, I had to create a new account.  Hence the name change.  

So, I am here to give you an update.  I will create a staging site and see how I get along with version 8 and see what happens.
Just wanted to give you this update so you did not think I abandoned you.

Will report back in due time.
